import React, { useState, useEffect } from 'react';
import { onMessage, postMessage } from '../../vscode';

interface ReportSection {
  id: string;
  type: string;
  title: string;
  content: string;
  order: number;
  autoGenerated: boolean;
}

interface ReportData {
  title: string;
  sections: ReportSection[];
  format: 'markdown' | 'latex';
}

export function ReportPreview() {
  const [report, setReport] = useState<ReportData | null>(null);
  const [editingSection, setEditingSection] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');

  useEffect(() => {
    onMessage((msg) => {
      if (msg.type === 'report:updated') {
        setReport(msg.payload as ReportData);
      }
    });
    postMessage('report:get');
  }, []);

  const handleEdit = (section: ReportSection) => {
    setEditingSection(section.id);
    setEditContent(section.content);
  };

  const handleSave = () => {
    if (editingSection) {
      postMessage('report:editSection', { sectionId: editingSection, content: editContent });
      setEditingSection(null);
    }
  };

  const handleExport = (format: string) => {
    postMessage('report:export', { format });
  };

  if (!report) {
    return (
      <div className="placeholder">
        <h3>No report generated yet</h3>
        <p>Complete a research pipeline to generate a report.</p>
      </div>
    );
  }

  return (
    <div>
      <div className="flex-between mb-24">
        <h2>{report.title}</h2>
        <div className="flex">
          <button onClick={() => handleExport('markdown')}>Export Markdown</button>
          <button className="secondary" onClick={() => handleExport('latex')}>Export LaTeX</button>
        </div>
      </div>

      {report.sections
        .sort((a, b) => a.order - b.order)
        .map(section => (
          <div key={section.id} className="card mb-16">
            <div className="flex-between mb-8">
              <h3>{section.title}</h3>
              <div className="flex">
                {section.autoGenerated && (
                  <span className="badge badge-running">AI Generated</span>
                )}
                {editingSection !== section.id ? (
                  <button className="secondary" onClick={() => handleEdit(section)}>Edit</button>
                ) : (
                  <div className="flex">
                    <button onClick={handleSave}>Save</button>
                    <button className="secondary" onClick={() => setEditingSection(null)}>Cancel</button>
                  </div>
                )}
              </div>
            </div>
            {editingSection === section.id ? (
              <textarea
                rows={15}
                value={editContent}
                onChange={e => setEditContent(e.target.value)}
                style={{ fontFamily: 'monospace' }}
              />
            ) : (
              <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.6 }}>
                {section.content}
              </div>
            )}
          </div>
        ))}
    </div>
  );
}
