export interface Paper {
  id: string;
  externalIds: {
    doi?: string;
    arxivId?: string;
    pmid?: string;
    semanticScholarId?: string;
  };
  title: string;
  authors: Author[];
  abstract: string;
  year: number;
  venue: string;
  url: string;
  pdfUrl?: string;
  source: 'arxiv' | 'semantic_scholar' | 'pubmed' | 'google_scholar' | 'web';
  citationCount?: number;
  summary?: string;
  methods?: ExtractedMethod[];
  hyperparameters?: ExtractedHyperparameter[];
  keyFindings?: string[];
  relevanceScore?: number;
  codeRepos?: string[];
  fetchedAt: number;
  analyzedAt?: number;
}

export interface Author {
  name: string;
  affiliations?: string[];
  authorId?: string;
}

export interface ExtractedMethod {
  name: string;
  description: string;
  category: string;
  paperSection: string;
}

export interface ExtractedHyperparameter {
  name: string;
  value: string;
  context: string;
  paperSection: string;
}

export interface ResearchSession {
  id: string;
  name: string;
  question: string;
  createdAt: number;
  updatedAt: number;
  status: 'active' | 'completed' | 'archived';
  pipelineId: string;
  papers: Paper[];
  experiments: Experiment[];
  report: Report | null;
  tags: string[];
  notes: string;
  llmConfig: LLMSessionConfig;
  tokenUsage: TokenUsage;
  schemaVersion: number;
}

export interface LLMSessionConfig {
  provider: string;
  model: string;
}

export interface Experiment {
  id: string;
  sessionId: string;
  name: string;
  description: string;
  status: 'configured' | 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';
  config: ExperimentConfig;
  runner: 'local' | 'docker' | 'slurm';
  startedAt?: number;
  completedAt?: number;
  metrics: Record<string, number>;
  logs: string;
  artifacts: Artifact[];
  basedOnPapers: string[];
  codeRepoUrl?: string;
}

export interface ExperimentConfig {
  command: string;
  args: string[];
  env: Record<string, string>;
  workingDirectory: string;
  dockerImage?: string;
  slurmOptions?: SlurmOptions;
  timeout?: number;
}

export interface SlurmOptions {
  partition: string;
  nodes: number;
  gpus: number;
  time: string;
  memory: string;
}

export interface Artifact {
  id: string;
  type: 'file' | 'figure' | 'table' | 'log' | 'model_checkpoint';
  name: string;
  path: string;
  mimeType: string;
  size: number;
  createdAt: number;
}

export interface Report {
  id: string;
  sessionId: string;
  title: string;
  sections: ReportSection[];
  references: BibEntry[];
  figures: ReportFigure[];
  format: 'markdown' | 'latex';
  generatedAt: number;
  exportedPath?: string;
}

export interface ReportSection {
  id: string;
  type: 'abstract' | 'introduction' | 'related_work' | 'methods' | 'experiments' | 'results' | 'discussion' | 'conclusion' | 'custom';
  title: string;
  content: string;
  order: number;
  autoGenerated: boolean;
}

export interface ReportFigure {
  id: string;
  caption: string;
  artifactId: string;
  sectionId: string;
}

export interface BibEntry {
  key: string;
  type: 'article' | 'inproceedings' | 'misc' | 'book';
  fields: Record<string, string>;
  paperId?: string;
}

export interface TokenUsage {
  totalPromptTokens: number;
  totalCompletionTokens: number;
  totalCost: number;
  byProvider: Record<string, { prompt: number; completion: number; cost: number }>;
  byStep: Record<string, { prompt: number; completion: number; cost: number }>;
}

export interface HyperTuningSession {
  id: string;
  sessionId: string;
  paramSpace: ParamDefinition[];
  constraints: ParamConstraint[];
  objective: TuningObjective;
  budget: TuningBudget;
  strategy: 'grid' | 'random' | 'bayesian' | 'llm-guided';
  command: string;
  trials: Trial[];
  bestTrialId?: string;
  status: 'configuring' | 'running' | 'paused' | 'completed';
  createdAt: number;
  updatedAt: number;
}

export interface ParamDefinition {
  name: string;
  type: 'float' | 'int' | 'choice' | 'bool';
  min?: number;
  max?: number;
  scale?: 'linear' | 'log';
  values?: (string | number | boolean)[];
  default?: string | number | boolean;
}

export interface ParamConstraint {
  rule: string;
  reason: string;
}

export interface TuningObjective {
  metric: string;
  direction: 'maximize' | 'minimize';
  secondaryMetrics?: { metric: string; direction: 'maximize' | 'minimize' }[];
}

export interface TuningBudget {
  maxTrials: number;
  maxTime?: string;
  maxCost?: number;
}

export interface Trial {
  id: string;
  number: number;
  params: Record<string, string | number | boolean>;
  metrics: Record<string, number>;
  status: 'pending' | 'running' | 'completed' | 'failed';
  startedAt?: number;
  completedAt?: number;
  duration?: number;
  logs?: string;
  error?: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export type Disposable = { dispose(): void };
